project:
  type: book
  output-dir: _book

book:
  title: "Essays in Empirical Finance"
  chapters:
    - index.qmd
    - chapters/00-publications.qmd
    - chapters/00-abstract.qmd
    - chapters/00-declaration.qmd
    - chapters/00-copyright.qmd
    - chapters/00-acknowledgements.qmd
    - chapters/01-introduction.qmd
    - chapters/02-paper-one.qmd
    - chapters/03-paper-two.qmd
    - chapters/04-paper-three.qmd
    - chapters/05-conclusion.qmd

format:
  uomthesis-journal-pdf: default
  uomthesis-journal-html: default

bibliography: references.bib
csl: _extensions/uomthesis-journal/csl/harvard-manchester.csl
