project:
  type: book
  output-dir: _book

book:
  title: "{{title}}"
  chapters:
    - index.qmd
    - chapters/00-abstract.qmd
    - chapters/00-acknowledgements.qmd
    - part: "Main body"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-literature.qmd
        - chapters/03-methodology.qmd
        - chapters/04-results.qmd
        - chapters/05-discussion.qmd
        - chapters/06-conclusion.qmd
  appendices:
    - chapters/appendix-a.qmd

format:
  uomthesis-standard-pdf: default
  uomthesis-standard-html: default

bibliography: references.bib
csl: _extensions/uomthesis-standard/csl/{{reference_style}}.csl
