- name: harvard-manchester
  url: https://raw.githubusercontent.com/citation-style-language/styles/master/harvard-cite-them-right.csl
  retrieved: '2026-06-02'
  sha256: 0ca3d2c7c881cd98cdd81098b5349f5921edf430498aa9a5a41918621cf7cc45
- name: apa
  url: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
  retrieved: '2026-06-02'
  sha256: 1ece4fb3c295e66d04b4394e295aa58a87741ceeef1658192437eb9953c2f13e
- name: chicago-author-date
  url: https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-author-date.csl
  retrieved: '2026-06-02'
  sha256: 002fade78d7e4fe9d42936a16b43a8066b097013f6255df40b1bfba6631eff9b
- name: mhra
  url: https://raw.githubusercontent.com/citation-style-language/styles/master/mhra-notes.csl
  retrieved: '2026-06-02'
  sha256: 9fa37e7faabf28795309b74b42c459b9586fd8f58529ed2db9f40722db3a7637
- name: vancouver
  url: https://raw.githubusercontent.com/citation-style-language/styles/master/elsevier-vancouver.csl
  retrieved: '2026-06-02'
  sha256: 005e915c3419eb2b84eb2b31bffc411dce3890619d3fd0ed23ac6591ac128335
